### ISSUE TITLE
problem in building 

### ISSUE THREAD

**Issue by Borelset** [Andiry/pmfs-3.19#3]
I try to build pmfs-new on a server runing linux-4.15, but in compiling, an error accured as below
```
/home/zxy/PMFS-new/super.c: In function ‘pmfs_get_block_info’:
/home/zxy/PMFS-new/super.c:110:27: error: passing argument 1 of ‘bdev_dax_supported’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  ret = bdev_dax_supported(sb, PAGE_SIZE);
                           ^~
In file included from /home/zxy/PMFS-new/super.c:35:0:
./include/linux/dax.h:44:20: note: expected ‘struct block_device *’ but argument is of type ‘struct super_block *’
 static inline bool bdev_dax_supported(struct block_device *bdev, int blocksize)
                    ^~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
scripts/Makefile.build:332: recipe for target '/home/zxy/PMFS-new/super.o' failed

```
what's going wrong?

**Comment by Andiry** [comment]
I am afraid you are not building against a 4.15 kernel. Please double check.

Here is the definition for bdev_dax_supported in 4.15:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/dax.h?h=linux-4.15.y#n44

You can see the first parameter is indeed a super_block*.

Anyway, the fix is trivial: either build on a 4.15 kernel, or change the parameter to sb->s_bdev.

**Comment by Borelset** [comment]
It is ubuntu 16.04
```
zxy@ubuntu:~/PMFS-new$ uname -a
Linux ubuntu 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
But the problem is solved by changing the parameter, thanks.

**Comment by Borelset** [comment]
> I am afraid you are not building against a 4.15 kernel. Please double check.
> 
> Here is the definition for bdev_dax_supported in 4.15:
> https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/include/linux/dax.h?h=linux-4.15.y#n44
> 
> You can see the first parameter is indeed a super_block*.
> 
> Anyway, the fix is trivial: either build on a 4.15 kernel, or change the parameter to sb->s_bdev.

It is ubuntu 16.04
```
zxy@ubuntu:~/PMFS-new$ uname -a
Linux ubuntu 4.15.0-45-generic #48~16.04.1-Ubuntu SMP Tue Jan 29 18:03:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
But the problem is solved by changing the parameter, thanks.
